databases:
    el:
        host: "s1-analytics-slave.eqiad.wmnet"
        port: 3306
        creds_file: /a/.my.cnf.research
        db: log
    commons:
        host: "s4-analytics-slave.eqiad.wmnet"
        port: 3306
        creds_file: /a/.my.cnf.research
        db: commonswiki
tables:
        upload_attempts: (SELECT id, uuid, clientIp, isTruncated, clientValidated, timestamp, webHost, wiki, event_appversion, event_device, event_filename, 0 as event_multiple, event_platform, event_result, event_source, event_username FROM MobileAppUploadAttempts_5257716 UNION SELECT * FROM MobileAppUploadAttempts_5334329) as MobileAppUploadAttempts
        edits_web: (SELECT timestamp, wiki, event_username, event_action, event_namespace, event_userEditCount FROM MobileWebEditing_5644223 UNION SELECT timestamp, wiki, event_username, event_action, event_namespace, event_userEditCount FROM MobileWebEditing_6077315) as MobileWebEditing
        login_attempts: MobileAppLoginAttempts_5257721
        share_attempts: MobileAppShareAttempts_5346170
        upload_web: (SELECT * FROM MobileWebUploads_5281063 UNION SELECT * FROM MobileWebUploads_5383883) AS MobileWebUploads
        cat_attempts: MobileAppCategorizationAttempts_5359208 # meow!
        account_creation: log.ServerSideAccountCreation_5487345
intervals:
        running_average: 30
output:
    path: /a/limn-public-data/mobile/datafiles
defaults:
    db: el
graphs:
        unique-uploaders:
                title: Unique uploaders (per month)
        unique-uploaders-day:
                title: Unique uploaders (per day)
        month-uploads:
                title: Uploads (per month)
        cancelled-uploads:
                title: Uploads cancelled by user (per day)
        error-uploads:
                title: Uploads failed because of an upload error (per day)
        successful-edits-newbie:
                title: Successful edits by first time users (per day)
        successful-edits-main:
                title: Successful Main namespace edits (per day)
        successful-edits-other:
                title: Successful other namespace edits (per day)
        successful-edits-unique:
                title: Successful unique user edits (per day)
        error-edits:
                title: Edits failed because of an error (per day)
        successful-logins:
                title: Successful logins (per day)
        successful-uploads:
                title: Successful Uploads (per day)
        share-attempts:
                title: Share Attempts (per day)
        uploaders-experience:
                title: Mobile Uploads vs Commons Edit count
        alltime-numbers:
                title: All time numbers
        no-cats: # Only puppies
                title: Percentage of files with a category added
        deleted-uploads:
                title: Uploads deleted (per month)
        edits-monthly-active-editors:
                title: Unique editors who made 5+ edits during this month on their mobile phone
        edits-monthly-unique-editors:
                title: Unique editors (per month)
        edits-monthly-successful:
                title: Successful edits (per month)
        edits-monthly-5plus-editors:
                title: Editors registered on mobile who made 5+ edits on enwiki (mobile+desktop)
        monthly-contributions:
                title: All monthly contributions on mobile
