databases:
    el:
        host: "s1-analytics-slave.eqiad.wmnet"
        port: 3306
        creds_file: /a/.my.cnf.research
        db: log
    commons:
        host: "s4-analytics-slave.eqiad.wmnet"
        port: 3306
        creds_file: /a/.my.cnf.research
        db: commonswiki
tables:
        upload_attempts: (SELECT id, uuid, clientIp, isTruncated, clientValidated, timestamp, webHost, wiki, event_appversion, event_device, event_filename, 0 as event_multiple, event_platform, event_result, event_source, event_username FROM MobileAppUploadAttempts_5257716 UNION SELECT * FROM MobileAppUploadAttempts_5334329) as MobileAppUploadAttempts
        login_attempts: MobileAppLoginAttempts_5257721
        share_attempts: MobileAppShareAttempts_5346170
        upload_web: (SELECT * FROM MobileWebUploads_5281063 UNION SELECT * FROM MobileWebUploads_5383883) AS MobileWebUploads
        navigation_timing: NavigationTiming_5336845
        cat_attempts: MobileAppCategorizationAttempts_5359208 # meow!
intervals:
        running_average: 30
output:
    path: /a/limn-public-data/mobile/datafiles
defaults:
    db: el
graphs:
        unique-uploaders:
                title: Unique uploaders (per month)
        unique-uploaders-day:
                title: Unique uploaders (per day)
        month-uploads:
                title: Uploads (per month)
        cancelled-uploads:
                title: Uploads cancelled by user (per day)
        error-uploads:
                title: Uploads failed because of an upload error (per day)
        successful-logins:
                title: Successful logins (per day)
        successful-uploads:
                title: Successful Uploads (per day)
        share-attempts:
                title: Share Attempts (per day)
        uploaders-experience:
                title: Mobile Uploads vs Commons Edit count
        alltime-numbers:
                title: All time numbers
        no-cats: # Only puppies
                title: Percentage of files with a category added
        deleted-uploads:
                title: Uploads deleted (per month)

        performance-rendering:
                title: Rendering time (ms)
