databases:
    el:
        host: "analytics-store.eqiad.wmnet"
        port: 3306
        creds_file: /a/.my.cnf.research
        db: log
    commons:
        host: "analytics-store.eqiad.wmnet"
        port: 3306
        creds_file: /a/.my.cnf.research
        db: commonswiki
tables:
        upload_attempts: (SELECT id, uuid, clientIp, isTruncated, clientValidated, timestamp, webHost, wiki, event_appversion, event_device, event_filename, 0 as event_multiple, event_platform, event_result, event_source, event_username FROM MobileAppUploadAttempts_5257716 UNION SELECT id, uuid, clientIp, isTruncated, clientValidated, timestamp, webHost, wiki, event_appversion, event_device, event_filename, event_multiple, event_platform, event_result, event_source, event_username FROM MobileAppUploadAttempts_5334329) as MobileAppUploadAttempts
        edits_web: (SELECT timestamp, wiki, event_username, event_action, event_namespace, event_userEditCount FROM MobileWebEditing_5644223 UNION SELECT timestamp, wiki, event_username, event_action, event_namespace, event_userEditCount FROM MobileWebEditing_6077315 UNION SELECT timestamp, wiki, event_username, event_action, event_namespace, event_userEditCount from MobileWebEditing_6637866 UNION SELECT timestamp, wiki, event_username, event_action, event_namespace, event_userEditCount from MobileWebEditing_7675117 UNION SELECT timestamp, wiki, event_username, event_action, event_namespace, event_userEditCount from MobileWebEditing_8599025) as MobileWebEditing
        login_attempts: MobileAppLoginAttempts_5257721
        share_attempts: MobileAppShareAttempts_5346170
        upload_web: (SELECT timestamp, wiki, event_action, event_funnel, event_username FROM MobileWebUploads_5281063 UNION SELECT timestamp, wiki, event_action, event_funnel, event_username FROM MobileWebUploads_5383883 UNION SELECT timestamp, wiki, event_action, event_funnel, event_username FROM MobileWebUploads_7967082 UNION SELECT timestamp, wiki, event_action, event_funnel, event_username FROM MobileWebUploads_8209043) AS MobileWebUploads
        cat_attempts: MobileAppCategorizationAttempts_5359208 # meow!
        account_creation: log.ServerSideAccountCreation_5487345
intervals:
        running_average: 30
output:
    path: /a/limn-public-data/mobile/datafiles
defaults:
    db: el
graphs:
        unique-uploaders:
                title: Unique uploaders (per month)
                frequency: hourly
        unique-uploaders-day:
                title: Unique uploaders (per day)
                frequency: hourly
        month-uploads:
                title: Uploads (per month)
                frequency: daily
        cancelled-uploads:
                title: Uploads cancelled by user (per day)
                frequency: hourly
        error-uploads:
                title: Uploads failed because of an upload error (per day)
                frequency: hourly
        successful-edits-newbie:
                title: Successful edits by first time users (per day)
                frequency: hourly
        successful-edits-main:
                title: Successful Main namespace edits (per day)
                frequency: hourly
        successful-edits-other:
                title: Successful other namespace edits (per day)
                frequency: hourly
        successful-edits-unique:
                title: Successful unique user edits (per day)
                frequency: hourly
        error-edits:
                title: Edits failed because of an error (per day)
                frequency: hourly
        successful-logins:
                title: Successful logins (per day)
                frequency: hourly
        successful-uploads:
                title: Successful Uploads (per day)
                frequency: hourly
        share-attempts:
                title: Share Attempts (per day)
                frequency: hourly
        uploaders-experience:
                title: Mobile Uploads vs Commons Edit count
                frequency: hourly
        alltime-numbers:
                title: All time numbers
                frequency: hourly
        no-cats: # Only puppies
                title: Percentage of files with a category added
                frequency: hourly
        deleted-uploads:
                title: Uploads deleted (per month)
                frequency: hourly
        edits-monthly-active-editors:
                title: Unique editors who became active with 5+ edits
                frequency: daily
        edits-monthly-unique-editors:
                title: Unique editors (per month)
                frequency: daily
        edits-monthly-successful:
                title: Successful edits (per month)
                frequency: daily
        edits-monthly-5plus-editors:
                title: Editors registered on mobile who made 5+ edits on enwiki (mobile+desktop)
                frequency: daily
                timeboxed: true
                starts: 2013-05-01
                # this graph is deprecated
                ends: 2013-05-01
        edits-monthly-active-2014:
                title: Editors who reached 5 mobile edits on enwiki within 30 days of registering
                frequency: daily
                timeboxed: true
                starts: 2013-05-01
        monthly-contributions:
                title: All monthly contributions on mobile
                frequency: daily
        thanks-daily:
                title: Thanks
                frequency: hourly
                starts: 2013-11-01
                timeboxed: true
        ui-daily:
                title: UI activity
                frequency: hourly
                starts: 2014-01-01
                timeboxed: true
        watchlist-activity:
                title: Watchlist activity
                frequency: hourly
                starts: 2014-01-01
                timeboxed: true
        mobile-options:
                title: Special:MobileOptions page activity
                frequency: hourly
                starts: 2014-04-16
                timeboxed: true
        diff-activity:
                title: Special:MobileDiff page activity
                frequency: hourly
                starts: 2014-01-01
                timeboxed: true
